

create table products(
    id bigint generated by default as identity,
    name jsonb null,
    description jsonb null,
    price jsonb null,
    image text null,
    constraint products_pkey primary key (id)
);


insert into products
    (name, description, price, image)
values
    (
        '{"en_US": "Spiky Cactus", "zh_CN": "仙人球"}', 
        '{"en_US": "A spiky yet elegant house cactus - perfect for the home or office. Origin and habitat: Probably native only to the Andes of Peru", "zh_CN": "一盆多刺而优雅的室内仙人掌 - 非常适合家居或办公室。起源与栖息地：可能仅原产于秘鲁安第斯山脉"}',
        '{"USD": 2095, "CNY": 14900}',
        'spiky_cactus.webp'
    ),
    (
        '{"en_US": "Tulip Pot", "zh_CN": "郁金香花盆"}',
        '{"en_US": "Bright crimson red species tulip with black centers, the poppy-like flowers will open up in full sun. Ideal for rock gardens, pots and border edging.", "zh_CN": "鲜红色的原种郁金香，中心呈黑色，花朵像罂粟一样在阳光下开放。非常适合岩石花园、盆栽和边缘修饰。"}',
        '{"USD": 1095, "CNY": 7800}',
        'tulip_pot.webp'
    ),
    (
        '{"en_US": "Aloe Vera", "zh_CN": "芦荟"}',
        '{"en_US": "Decorative Aloe vera makes a lovely house plant. A really trendy plant, Aloe vera is just so easy to care for.", "zh_CN": "装饰性的芦荟是一种可爱的室内植物。芦荟是非常时髦的植物，非常容易照料。"}',
        '{"USD": 1045, "CNY": 7400}',
        'aloe_vera.webp'
    ),
    (
        '{"en_US": "Fern Blechnum Gibbum", "zh_CN": "肋骨蕨"}',
        '{"en_US": "Create a tropical feel in your home with this lush green tree fern, it has decorative leaves and will develop a short slender trunk in time.", "zh_CN": "用这种郁郁葱葱的绿色树蕨在您的家中营造热带风情，它具有装饰性的叶子，并会随着时间的推移长出短而细的树干。"}',
        '{"USD": 1295, "CNY": 9200}',
        'fern_blechnum_gibbum.webp'
    ),
    (
        '{"en_US": "Assorted Indoor Succulents", "zh_CN": "什锦室内多肉植物"}',
        '{"en_US": "These assorted succulents come in a variety of different shapes and colours - each with their own unique personality.", "zh_CN": "这些什锦多肉植物有各种不同的形状和颜色 - 每一个都有自己独特的个性。"}',
        '{"USD": 4235, "CNY": 29900}',
        'assorted_indoor_succulents.webp'
    ),
    (
        '{"en_US": "Orchid", "zh_CN": "兰花"}',
        '{"en_US": "Gloriously elegant. It can go along with any interior as it is a neutral color and the most popular Phalaenopsis overall.", "zh_CN": "光彩照人，优雅大方。它可以搭配任何内饰，因为它是一种中性色，也是整体上最受欢迎的蝴蝶兰。"}',
        '{"USD": 3075, "CNY": 21800}',
        'orchid.webp'
    );
